# Generated by Django 4.2.6 on 2023-12-07 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Eventos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=50)),
                ("productora", models.CharField(max_length=50)),
                ("duracion", models.PositiveBigIntegerField()),
                ("imagenes", models.ImageField(upload_to="eventos")),
            ],
        ),
        migrations.CreateModel(
            name="Funcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("precio", models.PositiveBigIntegerField()),
                ("asientos_disponibles", models.PositiveBigIntegerField()),
                ("asientos_vendidos", models.PositiveBigIntegerField()),
                ("lugar", models.CharField(max_length=50)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.eventos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ventas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=50)),
                ("email", models.CharField(blank=True, max_length=50)),
                ("codigo", models.CharField(blank=True, max_length=50)),
                ("entradas", models.PositiveBigIntegerField()),
                ("total_original", models.PositiveBigIntegerField(default=0)),
                ("total_descuento", models.PositiveBigIntegerField(default=0)),
                ("total_final", models.PositiveBigIntegerField(default=0)),
                ("fecha", models.DateField()),
                (
                    "funcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.funcion",
                    ),
                ),
            ],
        ),
    ]
