# Generated by Django 5.0.4 on 2025-05-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_ubicacion_ventas_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventos',
            name='categoria',
            field=models.CharField(default='musica', max_length=50),
        ),
    ]
