# Generated by Django 5.0.4 on 2025-05-27 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_categoria_eventos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='mainApp.categoria'),
        ),
    ]
