# Generated by Django 5.0.4 on 2025-05-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_eventos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
