# Generated by Django 5.0.4 on 2025-05-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_categoria_nombre_alter_eventos_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='categoria',
        ),
    ]
