# Generated by Django 5.0.4 on 2025-05-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_remove_eventos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='categorias',
            field=models.ManyToManyField(related_name='eventos', to='mainApp.categoria'),
        ),
    ]
