# Generated by Django 5.0.4 on 2025-05-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_categoria_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
    ]
