# Generated by Django 5.0.4 on 2025-05-29 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_remove_categoria_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='categorias',
        ),
        migrations.AddField(
            model_name='categoria',
            name='funcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.funcion'),
        ),
    ]
