# Generated by Django 5.0.4 on 2025-05-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_remove_eventos_categorias_categoria_funcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='eventos',
            field=models.ManyToManyField(related_name='categorias', to='mainApp.eventos'),
        ),
    ]
