# Generated by Django 5.0.4 on 2025-05-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_categoria_slug_alter_categoria_funcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
