# Generated by Django 5.0.4 on 2025-05-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_alter_categoria_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='funcion',
        ),
    ]
