# Generated by Django 5.0.4 on 2025-05-29 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_remove_categoria_funcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='funcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.funcion'),
        ),
    ]
