# Generated by Django 5.0.4 on 2025-05-29 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_categoria_funcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='eventos',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='funcion',
        ),
        migrations.AddField(
            model_name='eventos',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.categoria'),
            preserve_default=False,
        ),
    ]
