# Generated by Django 5.0.4 on 2025-05-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_remove_eventos_categoria_categoria_eventos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='eventos',
        ),
    ]
