# Generated by Django 5.0.4 on 2025-05-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_remove_categoria_eventos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='funcion',
        ),
        migrations.AddField(
            model_name='eventos',
            name='categorias',
            field=models.ManyToManyField(related_name='eventos', to='mainApp.categoria'),
        ),
    ]
