# Generated by Django 5.0.4 on 2025-05-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_remove_categoria_funcion_eventos_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='categorias',
        ),
    ]
